before_script:
  #- set "BUILD_DIR=%CI_PROJECT_DIR%"
  #- set "BUILD_DIR=%BUILD_DIR:/=\%"
  - echo "Cleaning %BUILD_DIR%"
  #- del /q %BUILD_DIR%\*
  - rd /s /q %BUILD_DIR%\build
  # - for /d %%x in (%BUILD_DIR%\*) do if not "%%x\"=="%cd%\%BOOST_STAGEDIR%" @rd /s /q "%%x"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - powershell -File ./misc/CI/prepare_boost.ps1

cache:
  paths:
    - boost_bin/

build:
  tags:
    - windows-shell
  script:
    - git submodule update --init --recursive
    - md build
    - cd build
    - cmake -G Ninja -DBOOSTROOT=%URBI_WORKSPACE%\boost -DBOOST_LIBRARYDIR=%URBI_WORKSPACE%\boost\bin -DCMAKE_INSTALL_PREFIX=%URBI_WORKSPACE%\urbi_bin -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . -j4
    - cpack -G "WIX"
  artifacts:
    paths:
      - build/*.msi
    expire_in: 1 week
