include:
  - project: 'emysinc/utils/build-common'
    ref: master
    file: 'ci/gitlab-ci-general.yml'

build:
  extends: .build-general-config
  before_script:
    - call build-common\ci\scripts.cmd setupEnvironment
    - powershell -File ./misc/CI/prepare_boost.ps1
  script:
    - call build-common/ci/scripts.cmd buildAndProduceMsi -E env CXXFLAGS="/w" cmake -G Ninja -DBOOSTROOT=%CI_PROJECT_DIR:\=\\%\\boost_bin -DCMAKE_INSTALL_PREFIX=%CI_PROJECT_DIR%\urbi_bin -DCMAKE_BUILD_TYPE=Release -DGIT_REVISION=%CI_COMMIT_SHA% %CI_PROJECT_DIR%
    - call build-common/ci/scripts.cmd signAllMsi build/*.msi
    - call build-common/ci/scripts.cmd uploadToArtifactory
    - rmdir /Q /S ..\boost_1_68_0

upload-artifact-to-gitlab-release:
  extends: .upload-artifact-to-gitlab-release-general