set(COMMON_SRC
src/libuco/details.cc
src/libuco/local.mk
src/libuco/uevent.cc
src/libuco/uobject-common.cc
src/libuco/uobject-hub-common.cc
src/libuco/uprop.cc
src/libuco/ustarter.cc
src/libuco/utable.cc
src/libuco/uvar-common.cc
src/libuco/version-check.cc
src/libuvalue/exit.cc
src/libuvalue/package-info.cc
src/libuvalue/ubinary.cc
src/libuvalue/uimage.cc
src/libuvalue/ulist.cc
src/libuvalue/usound.cc
src/libuvalue/uvalue-common.cc
)

set(URBI_SRC
src/liburbi/compatibility.hh
src/liburbi/compatibility.hxx
src/liburbi/kernel-version.cc
src/liburbi/uabstractclient.cc
src/liburbi/uclient.cc
src/liburbi/uconversion.cc
src/liburbi/umain.cc
src/liburbi/umessage.cc
src/liburbi/urbi-launch.cc
src/liburbi/urbi-root.cc
src/liburbi/usyncclient.cc
src/liburbi/utag.cc
)

set(UOBJECT_REMOTE_SRC
  src/libuobject/main.cc
  src/libuobject/remote-ucontext-impl.hh
  src/libuobject/ucallbacks.cc
  src/libuobject/uobject.cc
  src/libuobject/utimer-callback.cc
  src/libuobject/uvar.cc
  src/libuco/urbi-main.cc
)

set(URBI_PUBLIC_HEADERS
urbi/customuvar.hh
urbi/customuvar.hxx
urbi/details.hh
urbi/exit.hh
urbi/export.hh
urbi/fwd.hh
urbi/input-port.hh
urbi/input-port.hxx
urbi/kernel-version.hh
urbi/package-info.hh
urbi/qt_umain.hh
urbi/revision-stub.hh
urbi/socket.hh
urbi/uabstractclient.hh
urbi/uabstractclient.hxx
urbi/ubinary.hh
urbi/ubinary.hxx
urbi/ublend-type.hh
urbi/ucallbacks.hh
urbi/uclient.hh
urbi/ucontext-factory.hh
urbi/ucontext.hh
urbi/ucontext.hxx
urbi/ucontext-impl.hh
urbi/ucontext-impl.hxx
urbi/uconversion.hh
urbi/uevent.hh
urbi/uevent.hxx
urbi/uexternal.hh
urbi/uimage.hh
urbi/uimage.hxx
urbi/ulist.hh
urbi/ulist.hxx
urbi/umain.hh
urbi/umessage.hh
urbi/umessage.hxx
urbi/uobject.hh
urbi/uobject-hub.hh
urbi/uobject.hxx
urbi/uproperty.hh
urbi/uprop.hh
urbi/urbi-root.hh
urbi/usound.hh
urbi/usound.hxx
urbi/ustarter.hh
urbi/ustarter.hxx
urbi/usyncclient.hh
urbi/utable.hh
urbi/utag.hh
urbi/utimer-callback.hh
urbi/uvalue.hh
urbi/uvalue.hxx
urbi/uvalue-serialize.hh
urbi/uvar.hh
urbi/uvar.hxx
urbi/version-check.hh
)
