set(COMMON_SRC
src/libuco/details.cc
src/libuco/local.mk
src/libuco/uevent.cc
src/libuco/uobject-common.cc
src/libuco/uobject-hub-common.cc
src/libuco/uprop.cc
src/libuco/ustarter.cc
src/libuco/utable.cc
src/libuco/uvar-common.cc
src/libuco/version-check.cc
src/libuvalue/exit.cc
src/libuvalue/package-info.cc
src/libuvalue/ubinary.cc
src/libuvalue/uimage.cc
src/libuvalue/ulist.cc
src/libuvalue/usound.cc
src/libuvalue/uvalue-common.cc
)

set(URBI_SRC
src/liburbi/compatibility.hh
src/liburbi/compatibility.hxx
src/liburbi/kernel-version.cc
src/liburbi/uabstractclient.cc
src/liburbi/uclient.cc
src/liburbi/uconversion.cc
src/liburbi/umain.cc
src/liburbi/umessage.cc
src/liburbi/urbi-launch.cc
src/liburbi/urbi-root.cc
src/liburbi/usyncclient.cc
src/liburbi/utag.cc
)

set(UOBJECT_REMOTE_SRC
  src/libuobject/main.cc
  src/libuobject/remote-ucontext-impl.hh
  src/libuobject/ucallbacks.cc
  src/libuobject/uobject.cc
  src/libuobject/utimer-callback.cc
  src/libuobject/uvar.cc
  src/libuco/urbi-main.cc
)

set(URBI_PUBLIC_HEADERS
include/urbi/customuvar.hh
include/urbi/customuvar.hxx
include/urbi/details.hh
include/urbi/exit.hh
include/urbi/export.hh
include/urbi/fwd.hh
include/urbi/input-port.hh
include/urbi/input-port.hxx
include/urbi/kernel-version.hh
include/urbi/package-info.hh
include/urbi/qt_umain.hh
include/urbi/revision-stub.hh
include/urbi/socket.hh
include/urbi/uabstractclient.hh
include/urbi/uabstractclient.hxx
include/urbi/ubinary.hh
include/urbi/ubinary.hxx
include/urbi/ublend-type.hh
include/urbi/ucallbacks.hh
include/urbi/uclient.hh
include/urbi/ucontext-factory.hh
include/urbi/ucontext.hh
include/urbi/ucontext.hxx
include/urbi/ucontext-impl.hh
include/urbi/ucontext-impl.hxx
include/urbi/uconversion.hh
include/urbi/uevent.hh
include/urbi/uevent.hxx
include/urbi/uexternal.hh
include/urbi/uimage.hh
include/urbi/uimage.hxx
include/urbi/ulist.hh
include/urbi/ulist.hxx
include/urbi/umain.hh
include/urbi/umessage.hh
include/urbi/umessage.hxx
include/urbi/uobject.hh
include/urbi/uobject-hub.hh
include/urbi/uobject.hxx
include/urbi/uproperty.hh
include/urbi/uprop.hh
include/urbi/urbi-root.hh
include/urbi/usound.hh
include/urbi/usound.hxx
include/urbi/ustarter.hh
include/urbi/ustarter.hxx
include/urbi/usyncclient.hh
include/urbi/utable.hh
include/urbi/utag.hh
include/urbi/utimer-callback.hh
include/urbi/uvalue.hh
include/urbi/uvalue.hxx
include/urbi/uvalue-serialize.hh
include/urbi/uvar.hh
include/urbi/uvar.hxx
include/urbi/version-check.hh
)
