name: Windows

on:
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - name: Qibuild
      run: python -m pip install qibuild
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.80.0
          # OPTIONAL: Specify a custon install location
          boost_install_dir: boost
          # OPTIONAL: Specify a platform version
          platform_version: 2022
          # OPTIONAL: Specify a toolset
          toolset: msvc
          link: shared
    - name: Checkout
      run: |
          qisrc init
          qisrc add https://github.com/urbiforge/libjpeg.git
          qisrc add https://github.com/urbiforge/gtest.git
          qisrc add https://github.com/urbiforge/libport.git
          qisrc add https://github.com/urbiforge/urbi.git
    - name: Configure
      run: qibuild configure --release urbi
      env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Build
      # Build your program with the given configuration
      run: qibuild make urbi
    - name: Install
      # Build your program with the given configuration
      run: qibuild install urbi urbisdk
    - uses: actions/upload-artifact@v3
      with:
        name: urbisdk-windows
        path: urbisdk/

