name: Linux

on:
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: dependencies
      run: sudo apt-get install -y libboost-all-dev
    - name: Version
      run: cd  $GITHUB_WORKSPACE/urbi && git describe --always > /tmp/version.txt
    - name: Configure
      run: mkdir  $GITHUB_WORKSPACE/build && cd  $GITHUB_WORKSPACE/build && cmake -DCMAKE_CXXFLAGS="-g -O2" -DCMAKE_INSTALL_PREFIX=/tmp/urbisdk ../urbi
    - name: Build
      # Build your program with the given configuration
      run: cd  $GITHUB_WORKSPACE/build && make -j2
    - name: Install
      # Build your program with the given configuration
      run: cd  $GITHUB_WORKSPACE/build && make install -j2
    - uses: actions/upload-artifact@v3
      with:
        name: urbisdk-linux
        path: /tmp/urbisdk
